#!/usr/bin/env python3
# This code is a Qiskit project.
#
# (C) Copyright IBM 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

import logging

from scripts.tool_runner import configure_logging, run_cmd

logger = logging.getLogger(__name__)

# Note that these are ordered from fastest to slowest.
CHECKS = {
    "notebook linters": ["tox", "-e", "lint"],
    "patterns index pages": ["npm", "run", "check:patterns-index"],
    "Qiskit bot": ["npm", "run", "check:qiskit-bot"],
    "metadata": ["npm", "run", "check:metadata"],
    "images": ["npm", "run", "check:images"],
    "orphan pages": ["npm", "run", "check:orphan-pages"],
    "spelling": ["npm", "run", "check:spelling"],
    "internal links": ["npm", "run", "check:internal-links"],
}


def main() -> None:
    for i, (name, cmd) in enumerate(CHECKS.items()):
        run_cmd(name, cmd, progress=f"{i + 1}/{len(CHECKS)}")
    logger.info("🎉 All checks passed!")


if __name__ == "__main__":
    try:
        configure_logging()
        main()
    except KeyboardInterrupt:
        raise SystemExit(1)
