#!/usr/bin/env python3
# This code is a Qiskit project.
#
# (C) Copyright IBM 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

import logging
from pathlib import Path

from scripts.tool_runner.qiskit_docs_contributor_tools import (
    configure_logging,
    run_cmd,
    check_packages,
    install_node_dependencies,
)

logger = logging.getLogger(__name__)

# Note that these are ordered from fastest to slowest.
CHECKS = {
    "notebook linters": ["tox", "-e", "lint"],
    "all notebooks are tested": ["python3", "scripts/ci/check-all-notebooks-are-tested.py"],
    "Qiskit bot": ["npm", "run", "check:qiskit-bot"],
    "tutorials index page": ["python3", "scripts/ci/check-tutorials-index.py"],
    "markdown": ["npm", "run", "check:markdown"],
    "orphan pages": ["npm", "run", "check:orphan-pages"],
    "spelling": ["npm", "run", "check:spelling"],
    "internal links": ["npm", "run", "check:internal-links"],
}


def main() -> None:
    check_packages()
    if not Path("./node_modules").exists():
        install_node_dependencies()
    for i, (name, cmd) in enumerate(CHECKS.items()):
        run_cmd(name, cmd, progress=f"{i + 1}/{len(CHECKS)}")
    logger.info("🎉 All checks passed!")


if __name__ == "__main__":
    try:
        configure_logging()
        main()
    except KeyboardInterrupt:
        raise SystemExit(1)
