#!/usr/bin/env python3
# This code is a Qiskit project.
#
# (C) Copyright IBM 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from scripts.tool_runner import configure_logging, run_cmd


def main() -> None:
    run_cmd("notebook formatters", ["tox", "-e", "fix"], progress=None)


if __name__ == "__main__":
    try:
        configure_logging()
        main()
    except KeyboardInterrupt:
        raise SystemExit(1)
