#!/usr/bin/env python3
# This code is a Qiskit project.
#
# (C) Copyright IBM 2025.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from scripts.tool_runner.qiskit_docs_contributor_tools import (
    configure_logging,
    check_packages,
    install_node_dependencies,
)


def main() -> None:
    print("Checking for installed packages...")
    check_packages(verbose=True)
    install_node_dependencies()


if __name__ == "__main__":
    try:
        configure_logging()
        main()
    except KeyboardInterrupt:
        raise SystemExit(1)
