---
title: MinimumEigensolverFactory
description: API reference for qiskit.chemistry.algorithms.MinimumEigensolverFactory
in_page_toc_min_heading_level: 1
python_api_type: class
python_api_name: qiskit.chemistry.algorithms.MinimumEigensolverFactory
---

# qiskit.chemistry.algorithms.MinimumEigensolverFactory

<span id="qiskit.chemistry.algorithms.MinimumEigensolverFactory" />

`MinimumEigensolverFactory` [GitHub](https://github.com/qiskit-community/qiskit-aqua/tree/stable/0.9/qiskit/chemistry/algorithms/ground_state_solvers/minimum_eigensolver_factories/minimum_eigensolver_factory.py "view source code")

A factory to construct a minimum eigensolver based on a qubit operator transformation.

### \_\_init\_\_

<span id="qiskit.chemistry.algorithms.MinimumEigensolverFactory.__init__" />

`__init__()`

Initialize self. See help(type(self)) for accurate signature.

## Methods

|                                                                                                                                                                                            |                                                                                         |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------- |
| [`__init__`](#qiskit.chemistry.algorithms.MinimumEigensolverFactory.__init__ "qiskit.chemistry.algorithms.MinimumEigensolverFactory.__init__")()                                           | Initialize self.                                                                        |
| [`get_solver`](#qiskit.chemistry.algorithms.MinimumEigensolverFactory.get_solver "qiskit.chemistry.algorithms.MinimumEigensolverFactory.get_solver")(transformation)                       | Returns a minimum eigensolver, based on the qubit operator transformation.              |
| [`supports_aux_operators`](#qiskit.chemistry.algorithms.MinimumEigensolverFactory.supports_aux_operators "qiskit.chemistry.algorithms.MinimumEigensolverFactory.supports_aux_operators")() | Returns whether the eigensolver generated by this factory supports auxiliary operators. |

### get\_solver

<span id="qiskit.chemistry.algorithms.MinimumEigensolverFactory.get_solver" />

`abstract get_solver(transformation)`

Returns a minimum eigensolver, based on the qubit operator transformation.

**Parameters**

**transformation** (`Transformation`) – The qubit operator transformation.

**Return type**

`MinimumEigensolver`

**Returns**

A minimum eigensolver suitable to compute the ground state of the molecule transformed by `transformation`.

### supports\_aux\_operators

<span id="qiskit.chemistry.algorithms.MinimumEigensolverFactory.supports_aux_operators" />

`abstract supports_aux_operators()`

Returns whether the eigensolver generated by this factory supports auxiliary operators.

**Return type**

`bool`

