name: 🪲 Content bug or inaccuracy with non-API docs
description: Report typos, bugs, out-of-date content, broken links, etc.
labels: ["bug 🐛", "content 📄", "needs triage 🤔"]
assignees:
  - abbycross
  - beckykd

body:
  - type: markdown
    attributes:
      value: Thank you for reporting!  Please also use the search to see if there are any other relevant issues or pull requests.
  - type: markdown
    attributes:
      value: |
        ⚠️ Note that this repository is only for non-API content that is hosted at https://docs.quantum.ibm.com/.
  - type: markdown
    attributes:
      value: |
        * If your issue concerns Qiskit API content, open an issue in the [Qiskit repository](https://github.com/Qiskit/qiskit/issues/new/choose).
  - type: markdown
    attributes:
      value: |
        * If your issue concerns Qiskit Runtime API content, open an issue in the [Qiskit IBM Runtime repository](https://github.com/Qiskit/qiskit-ibm-runtime/issues/new/choose).
  - type: markdown
    attributes:
      value: |
        * If your issue concerns a Qiskit Ecosystem project, open an issue in the relevant [Ecosystem project repository](https://qiskit.github.io/ecosystem/).

  - type: textarea
    attributes:
      label: URL to the relevant documentation
      description: provide a URL and section name/paragraph if applicable
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Select all that apply
      description: Please select all that apply from the following.
      options:
        - label: typo
        - label: code bug
        - label: out-of-date content
        - label: broken link
        - label: other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the fix.
      description: >
        If reporting a bug, please be as specific as possible (steps to reproduce, screenshot, etc.).
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thank you for your feedback! If you are interested in joining the IBM Quantum Feedback Program, <a href="https://www.ibm.com/quantum/feedback-program">sign up here</a>.
