name: ✨ Request new content
description: Make a request to the Content Team to add a new section in the docs.
labels: ["content request", "needs triage 🤔", "content 📄"]
assignees:
  - abbycross
  - beckykd

body:
  - type: markdown
    attributes:
      value: Thank you for your request!  Upon receiving your new content request, we will review it with the team. We will add anything that is  determined to be in line with the goals and intentions of this documentation.
  - type: markdown
    attributes:
      value: |
        ⚠️ Note that this repository is only for non-API content that is hosted at https://docs.quantum.ibm.com/.
  - type: markdown
    attributes:
      value: |
        * If your issue concerns Qiskit API content, open an issue in the [Qiskit repository](https://github.com/Qiskit/qiskit/issues/new/choose).
  - type: markdown
    attributes:
      value: |
        * If your issue concerns Qiskit Runtime API content, open an issue in the [Qiskit IBM Runtime repository](https://github.com/Qiskit/qiskit-ibm-runtime/issues/new/choose).
  - type: markdown
    attributes:
      value: |
        * If your issue concerns a Qiskit Ecosystem project, open an issue in the relevant [Ecosystem project repository](https://qiskit.github.io/ecosystem/).

  - type: textarea
    attributes:
      label: URL, if applicable
      description: Provide a URL and section name/paragraph where the new content belongs, if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the new content you are requesting.
      description: >
        Please give a clear and concise description. What value does the new content bring?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: If this new content request is accepted, do you want to write the content?
      description:
      multiple: false
      options:
        - I will write a draft of the proposed content
        - I can help the team by providing enough information to write the material
        - I only want to review the material when it's finished
        - "no"
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thank you for your feedback! If you are interested in joining the IBM Quantum Feedback Program, <a href="https://www.ibm.com/quantum/feedback-program">sign up here</a>.
