name: ✨ Request new content
description: Make a request to the Content Team to add a new section in the docs.
labels: ["NEW CONTENT REQUEST ✨"]
assignees:
  - abbycross
  - beckykd
  - javabster

body:
  - type: markdown
    attributes:
      value: Thank you for your request!  Upon receiving your new content request, we will review it with the team. We will add anything that is  determined to be in line with the goals and intentions of this documentation.

  - type: textarea
    attributes:
      label: URL, if applicable
      description: Provide a URL and section name/paragraph where the new content belongs, if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the new content you are requesting.
      description: >
        Please give a clear and concise description. What value does the new content bring?
    validations:
      required: true

  - type: radio
    attributes:
      label: If this new content request is accepted, will you write a draft the content, or help the team draft it?
      options:
        one: I will write a draft of the proposed content
        two: I can help the team by providing enough information to write the material
        three: I only want to review the material when it's finished
    validations:
      required: true