name: UI issue or feature request 📱
description: Report a rendering or other visual problem with the user interface, or request a new feature.
labels: ["UI feedback", "infra 🏗️"]
assignees:
  - Qiskit/docs-content-team
  - javabster
  - Eric-Arellano

body:
  - type: markdown
    attributes:
      value: Thank you for reporting!  Please also use the search to see if there are any other relevant issues or pull requests.

  - type: textarea
    attributes:
      label: URL to the relevant documentation
      description: provide a URL and section name/paragraph if applicable
    validations:
      required: false

  - type: textarea
    attributes:
      label: Please describe the UI problem or feature request.
      description: >
        Please be as specific as possible. Include steps to reproduce, the operating system and browser you're using, a screenshot if possible, etc.
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thank you for your feedback! If you are interested in joining the IBM Quantum Feedback Program, <a href="https://www.ibm.com/quantum/feedback-program">sign up here</a>.
