# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Notebook testing setup
description: Set up Python, tox, and IBM Quantum account
inputs:
  install-linux-deps:
    description: Whether to install extra dependencies
    default: "false"
  ibm-cloud-token:
    description: "Token for quantum.cloud.ibm.com"
    required: true
  instance:
    description: "CRN for quantum.cloud.ibm.com"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python packages
      shell: bash
      run: pip install tox qiskit-ibm-runtime

    - name: Save IBM Quantum account
      shell: python
      run: |
        from qiskit_ibm_runtime import QiskitRuntimeService

        if "${{ inputs.ibm-cloud-token }}" == "":
          print(
            "Token is an empty string, this can happen when making a PR from a "
            "fork. We will continue without setting up the account as not all "
            "notebooks need a valid account to run."
          )
        else:
          QiskitRuntimeService.save_account(
              channel="ibm_cloud",
              instance="${{ inputs.instance }}",
              token="${{ inputs.ibm-cloud-token }}",
              set_as_default=True
          )
          # Need to save the account with the 'ibm_quantum_platform' channel since some of the
          #  functions notebooks use it.
          QiskitRuntimeService.save_account(
              channel="ibm_quantum_platform",
              instance="${{ inputs.instance }}",
              token="${{ inputs.ibm-cloud-token }}",
          )

    - name: Install Linux dependencies
      if: ${{ inputs.install-linux-deps == 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install texlive-pictures texlive-latex-extra poppler-utils graphviz imagemagick
        sudo ln -s /usr/bin/convert /usr/bin/magick

    - name: Set ulimit
      # https://github.com/Qiskit/documentation/issues/2387#issuecomment-2523753374
      shell: bash
      run: ulimit -n 6000
