// This code is a Qiskit project.
//
// (C) Copyright IBM 2024.
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE file in the root directory
// of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

// Pipeline for generating addon content pages from a Sphinx build artifact.
// Addon docs differ from API docs in several ways:
//   - Content lives under docs/addons/{pkg}/ rather than docs/api/{pkg}/.
//   - The Sphinx artifact contains how-to guides and explanations (HTML),
//     Jupyter notebooks (.ipynb), and static images — but NOT apidoc stubs.
//   - A _toc.json is generated by generateAddonToc (not generateToc) because
//     the TOC shape for addons includes a back-link to the parent page and
//     optional Tutorials and API reference sections.
//   - When a notebook and an HTML file share the same base name, the notebook
//     wins so we preserve code outputs rather than the rendered HTML version.

import { writeFile } from "fs/promises";

import { globby } from "globby";
import { mkdirp } from "mkdirp";

import { ObjectsInv } from "./objectsInv.js";
import { Pkg } from "./Pkg.js";
import {
  convertHtmlToMarkdown,
  copyImages,
  postProcess,
  writeMarkdownResults,
} from "./pipelineStages.js";
import {
  collectNotebookImages,
  processNotebooks,
  readNotebooks,
  writeNotebooks,
} from "./notebookStages.js";
import { DOCS_BASE_PATH } from "./paths.js";
import { generateAddonToc } from "./generateAddonToc.js";

// Sphinx build artifacts that are never content.
const SPHINX_INTERNALS = [
  "_static/**",
  "_sources/**",
  "_downloads/**",
  "_modules/**",
  "genindex.html",
  "py-modindex.html",
  "search.html",
  "objects.inv",
];

/**
 * Run the full addon docs pipeline for one package version.
 *
 * @param artifactPath    Root of the Sphinx HTML build (the unzipped artifact folder).
 * @param docsBaseFolder  Repo-relative output root for markdown, e.g. "docs/addons".
 * @param publicBaseFolder Repo-relative output root for public assets, e.g. "public/docs".
 * @param pkg             Package metadata (name, version, tutorial slugs, etc.).
 */
export async function runAddonDocsPipeline(
  artifactPath: string,
  docsBaseFolder: string,
  publicBaseFolder: string,
  pkg: Pkg,
): Promise<void> {
  const allObjectInvs = await ObjectsInv.loadPublishedApis(publicBaseFolder);
  const [files, outputPath, objectsInv] = await determineFilePaths(
    artifactPath,
    docsBaseFolder,
    pkg,
  );

  // HTML → Markdown. The last argument (true) enables extracting frontmatter
  // from the Sphinx HTML <h1> rather than letting addFrontMatter.ts generate it.
  const htmlFiles = files.filter((f) => f.endsWith(".html"));
  const initialResults = await convertHtmlToMarkdown(
    pkg,
    artifactPath,
    docsBaseFolder,
    outputPath,
    htmlFiles,
    pkg.outputDir(`${DOCS_BASE_PATH}/images/addons`),
    true,
  );

  const results = await postProcess(
    pkg,
    initialResults,
    objectsInv,
    allObjectInvs,
  );
  await writeMarkdownResults(pkg, docsBaseFolder, results);

  // Notebooks. Images embedded in notebooks are collected separately so they
  // can be passed to copyImages together with the HTML-derived images.
  const notebookFiles = files.filter((f) => f.endsWith(".ipynb"));
  const initialNotebooks = await readNotebooks(
    artifactPath,
    docsBaseFolder,
    outputPath,
    notebookFiles,
  );
  const imageDestination = pkg.outputDir(`${DOCS_BASE_PATH}/images/addons`);
  const notebookImages = collectNotebookImages(
    initialNotebooks,
    imageDestination,
  );
  const notebooks = processNotebooks(
    initialNotebooks,
    objectsInv,
    allObjectInvs,
    pkg,
    imageDestination,
  );
  await writeNotebooks(pkg, docsBaseFolder, notebooks);

  // Copy all images (HTML-referenced + notebook-referenced) into public/.
  await copyImages(
    pkg,
    artifactPath,
    pkg.outputDir(`${publicBaseFolder}/images/addons`),
    results,
    notebookImages,
  );

  console.log("Generating addon toc");
  const toc = await generateAddonToc(pkg, docsBaseFolder, artifactPath);
  await writeFile(
    `${outputPath}/_toc.json`,
    JSON.stringify(toc, null, 2) + "\n",
  );
}

async function determineFilePaths(
  htmlPath: string,
  docsBaseFolder: string,
  pkg: Pkg,
): Promise<[string[], string, ObjectsInv]> {
  const objectsInv = await ObjectsInv.fromFile(htmlPath, pkg.language);

  const allFiles = await globby(["**"], {
    cwd: htmlPath,
    ignore: [
      "apidocs/**",
      "apidoc/**",
      "stubs/**",
      "tutorials/**",
      "release-notes.html",
      "release_notes.html",
      ...SPHINX_INTERNALS,
    ],
  });

  // Prefer .ipynb over .html when both exist for the same base path.
  const notebookBases = new Set(
    allFiles
      .filter((f) => f.endsWith(".ipynb"))
      .map((f) => f.slice(0, -".ipynb".length)),
  );
  const files = allFiles.filter(
    (f) =>
      !f.endsWith(".html") || !notebookBases.has(f.slice(0, -".html".length)),
  );
  const outputPath = pkg.outputDir(docsBaseFolder);
  await mkdirp(outputPath);
  return [files, outputPath, objectsInv];
}
