# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: API checks
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/api/**/*"
      - "public/api/**/*"
      - "public/images/api/**/*"
      - "scripts/js/**/*"
      - ".github/workflows/api-checks.yml"

jobs:
  api-checks:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: npm ci
      - name: Check internal links
        run: >
          npm run check:internal-links --
          --current-apis
          --dev-apis
          --historical-apis
          --qiskit-legacy-release-notes
      - name: Check for orphan pages
        run: npm run check:orphan-pages -- --apis
      - name: Check metadata
        run: npm run check:metadata -- --apis
      - name: Check images
        run: npm run check:images -- --apis
