# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Check if Qiskit deprecation is needed in version selector
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1,2,3,4,5" # At 01:00 on Monday-Friday.

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Check release age and make issue
        run: npm run check:qiskit-deprecation
