# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# This Action uploads the English documentation to Crowdin so that it can be
# translated.
#
# We upload on every merge to `main` rather than batching changes.
# The Translations team prefers that workflow: it lets them get
# started on changes right away and makes the changes less
# overwhelming since they're smaller.

name: Upload English to Crowdin
on:
  push:
    branches: [main]
    paths:
      - "docs/**/*"
      - "!docs/api/qiskit/**/*"
      - "!docs/api/qiskit-ibm-runtime/**/*"
      - "!docs/api/qiskit-ibm-provider/**/*"
  workflow_dispatch:

jobs:
  upload-english:
    if: github.repository_owner == 'Qiskit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload English
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_sources: false
          download_translations: false
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
