# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: PR preview cleanup
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  preview-cleanup:
    name: PR preview cleanup
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clean up PR previews
        run: scripts/pr-previews/cleanup.py
        env:
          GH_TOKEN: ${{ github.token }}
